/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package array;

/**
 *
 * @author RAFLI NUR FAUZI P
 */
public class pilihdokter extends javax.swing.JFrame {

    /**
     * Creates new form pilihdokter
     */
    public pilihdokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pilih = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        spesialis = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        usia = new javax.swing.JTextField();
        kelamin = new javax.swing.JTextField();
        darah = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        negara = new javax.swing.JTextField();
        praktek = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setText("PILIHAN DOKTER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 20, 83, 14);

        pilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu --", "DR. Farras Yassar", "DR. Dian Sikahita", "DR. Harun Ulum Fajar", "DR. RAFLI NUR FAUZI PRATAMA", " " }));
        pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihActionPerformed(evt);
            }
        });
        getContentPane().add(pilih);
        pilih.setBounds(130, 80, 140, 20);

        jLabel3.setText("PILIH DOKER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 80, 14);

        jLabel4.setText("NAMA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 130, 80, 14);

        jLabel5.setText("ALAMAT");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 170, 80, 14);

        jLabel6.setText("USIA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 210, 80, 14);

        jLabel7.setText("JENIS KELAMIN");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 250, 80, 14);

        jLabel8.setText("GOLONGAN DARAH");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 290, 100, 14);

        jLabel9.setText("STATUS");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 330, 80, 14);

        jLabel10.setText("KEWARGANEGARAAN");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 370, 110, 14);

        jLabel12.setText("DOKTER SPESIALIS");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 440, 100, 14);

        jLabel11.setText("WAKTU PRAKTEK");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 410, 100, 14);

        spesialis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spesialisActionPerformed(evt);
            }
        });
        getContentPane().add(spesialis);
        spesialis.setBounds(130, 440, 140, 30);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(130, 120, 140, 30);
        getContentPane().add(alamat);
        alamat.setBounds(130, 160, 140, 30);

        usia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usiaActionPerformed(evt);
            }
        });
        getContentPane().add(usia);
        usia.setBounds(130, 200, 140, 30);

        kelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelaminActionPerformed(evt);
            }
        });
        getContentPane().add(kelamin);
        kelamin.setBounds(130, 240, 140, 30);

        darah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darahActionPerformed(evt);
            }
        });
        getContentPane().add(darah);
        darah.setBounds(130, 280, 140, 30);

        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        getContentPane().add(status);
        status.setBounds(130, 320, 140, 30);

        negara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negaraActionPerformed(evt);
            }
        });
        getContentPane().add(negara);
        negara.setBounds(130, 360, 140, 30);

        praktek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                praktekActionPerformed(evt);
            }
        });
        getContentPane().add(praktek);
        praktek.setBounds(130, 400, 140, 30);

        setBounds(0, 0, 416, 532);
    }// </editor-fold>//GEN-END:initComponents

    private void pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihActionPerformed
        // TODO add your handling code here:
        if (pilih.getSelectedItem().equals("DR. Farras Yassar")){
            nama.setText("DR. Farras Yassar ");
            alamat.setText("Jln. sudirman, Pasuruan");
            usia.setText("31 Tahun");
            kelamin.setText("Laki laki");
            darah.setText("A");
            status.setText("kawin");
            negara.setText("negro");
            spesialis.setText("Dokter Bedah otak");
            praktek.setText("Pagi (06.30 - 16.00)");
            
        }
        
        else
            if (pilih.getSelectedItem().equals("DR.Dian Sikahita")){
            nama.setText("DR.Dian Sikahita ");
            alamat.setText("Jln. imam bojol, Malang");
            usia.setText("27 Tahun");
            kelamin.setText("Perempuan");
            darah.setText("A");
            status.setText("Menikah");
            negara.setText("arab");
            spesialis.setText("Dokter Kandungan");
            praktek.setText("Siang (12.30 - 19.00)");
            
        }
        
        else
            if (pilih.getSelectedItem().equals("DR. Harun Ulum Fajar")){
            nama.setText("DR.Harun Ulum Fajar ");
            alamat.setText("Jln. alhuda, jogja");
            usia.setText("35 Tahun");
            kelamin.setText("Perempuan");
            darah.setText("0");
            status.setText("Tunangan");
            negara.setText("Indonesia");
            spesialis.setText("Dokter Anak ");
            praktek.setText("Pagi (07.30 - 17.00)");
            }
            
         else
            if (pilih.getSelectedItem().equals("DR. RAFLI NUR FAUZI PRATAMA")){
            nama.setText("DR. RAFLI NUR FAUZI PRATAMA ");
            alamat.setText("Jln. Semeru 45, PONOROGO");
            usia.setText("23 Tahun");
            kelamin.setText("Laki - Laki");
            darah.setText("A");
            status.setText("Menikah");
            negara.setText("MALAYSIA");
            spesialis.setText("Dokter Umum");
            praktek.setText("Malam (17.00 - 24.00)");
            
            }    
    }//GEN-LAST:event_pilihActionPerformed

    private void spesialisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spesialisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spesialisActionPerformed

    private void usiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usiaActionPerformed

    private void kelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelaminActionPerformed

    private void darahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_darahActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void negaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_negaraActionPerformed

    private void praktekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_praktekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_praktekActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pilihdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pilihdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pilihdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pilihdokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pilihdokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField darah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kelamin;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField negara;
    private javax.swing.JComboBox<String> pilih;
    private javax.swing.JTextField praktek;
    private javax.swing.JTextField spesialis;
    private javax.swing.JTextField status;
    private javax.swing.JTextField usia;
    // End of variables declaration//GEN-END:variables
}
