/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package array;

/**
 *
 * @author Bethaa
 */
public class Praktikum2 extends javax.swing.JFrame {
    String jns = "";
    int jml;
    
    /**
     * Creates new form Praktikum2
     */
    public Praktikum2() {
        initComponents();
        getJumlah();
        setJenis();
        Panel.setVisible(false);
        jumlah.setVisible(true);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        bil1.setVisible(false);
        bil2.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ket = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bil1 = new javax.swing.JLabel();
        bil2 = new javax.swing.JLabel();
        bil3 = new javax.swing.JLabel();
        bil4 = new javax.swing.JLabel();
        jumlah = new javax.swing.JComboBox<>();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        b4 = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 102, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Browallia New", 0, 10)); // NOI18N
        setForeground(java.awt.Color.yellow);

        jLabel1.setText("PROGRAM ARITMATIKA");

        jLabel2.setText("Jenis Aritmatika");

        jenis.setBackground(new java.awt.Color(0, 153, 153));
        jenis.setEditable(true);
        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih", "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });

        Panel.setBackground(new java.awt.Color(153, 255, 153));
        Panel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 0)));
        Panel.setForeground(new java.awt.Color(0, 255, 153));
        Panel.setLayout(null);

        jLabel3.setText("Operasi");
        Panel.add(jLabel3);
        jLabel3.setBounds(10, 0, 70, 30);
        Panel.add(ket);
        ket.setBounds(110, 20, 170, 30);

        jLabel4.setText("Jumlah Bilangan");
        Panel.add(jLabel4);
        jLabel4.setBounds(30, 70, 100, 30);

        bil1.setText("Bilangan 1");
        Panel.add(bil1);
        bil1.setBounds(30, 110, 80, 30);

        bil2.setText("Bilangan 2");
        Panel.add(bil2);
        bil2.setBounds(30, 150, 80, 30);

        bil3.setText("Bilangan 3");
        Panel.add(bil3);
        bil3.setBounds(30, 190, 70, 30);

        bil4.setText("Bilangan 4");
        Panel.add(bil4);
        bil4.setBounds(30, 230, 70, 30);

        jumlah.setBackground(new java.awt.Color(255, 255, 51));
        jumlah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        Panel.add(jumlah);
        jumlah.setBounds(130, 70, 210, 30);
        Panel.add(b1);
        b1.setBounds(130, 110, 210, 30);
        Panel.add(b2);
        b2.setBounds(130, 150, 210, 30);
        Panel.add(b3);
        b3.setBounds(130, 190, 210, 30);

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        Panel.add(b4);
        b4.setBounds(130, 230, 210, 30);

        hitung.setBackground(new java.awt.Color(0, 102, 102));
        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        Panel.add(hitung);
        hitung.setBounds(180, 280, 100, 23);
        Panel.add(hasil);
        hasil.setBounds(30, 330, 320, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
        setJenis();}
    
    public void setJenis(){
        if(jenis.getSelectedItem().equals("Penjumlahan")){
            jns = "Penjumlahan";
            ket.setText("Penjumlahan");
            Panel.setVisible(true);
           jumlah.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pengurangan")){
            jns = "Pengurangan";
            ket.setText("Pengurangan");
            Panel.setVisible(true);
            jumlah.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Perkalian")){
            jns = "Perkalian";
            ket.setText("Perkalian");
            Panel.setVisible(true);
            jumlah.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pembagian")){
            jns = "Pembagian";
            ket.setText("Pembagian");
            Panel.setVisible(true);
            jumlah.setEnabled(true);
        }
        
  
    }//GEN-LAST:event_jenisActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
        getJumlah();
    }
    public void getJumlah(){
        if(jumlah.getSelectedItem().equals("2")){
            bil3.setVisible(false);
            bil4.setVisible(false);
            b3.setVisible(false);
            b4.setVisible(false);
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            jml = 2; 
                 
        } else if(jumlah.getSelectedItem().equals("3")){
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(false);
            b3.setVisible(true);
            b4.setVisible(false);
            jml = 3; 
        } else if(jumlah.getSelectedItem().equals("4")){
            bil1.setVisible(true);
            bil2.setVisible(true);
            b1.setVisible(true);
            b2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
            jml = 4; }
        
    }//GEN-LAST:event_jumlahActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        Double hsl = 0.0;
        Double a1, a2, a3, a4;
        a1 = Double.parseDouble(b1.getText().toString());
        a2 = Double.parseDouble(b2.getText().toString());
        a3 = Double.parseDouble(b3.getText().toString());
        a4 = Double.parseDouble(b4.getText().toString());
        
        if(jns.equals("Penjumlahan")){
            if(jml == 2){
                hsl = a1 + a2;
                hasil.setText("" + a1 + "+" + a2 + "=" + hsl);
            }
            
            if(jml == 3){
                hsl = a1 + a2 + a3;
                hasil.setText("" + a1 + "+" + a2 + "+" + a3 + "=" + hsl);
            }
            if(jml == 4){
                hsl = a1 + a2 + a3 + a4;
                hasil.setText("" + a1 + " + " + a2 + " + " + a3 + " + " + a4 + " = " + hsl);
            }
        }
        else if(jns.equals("Pengurangan")){
            if(jml == 2){
                hsl = a1 - a2;
                hasil.setText(" " + a1 + " - " + a2 + " = " + hsl);
            }
            if(jml == 3){
                hsl = a1 - a2 - a3;
                hasil.setText(" " + a1 + " - " + a2 + " - " + a3 + " = " + hsl);
            }
            if(jml == 4){
                hsl = a1 - a2 - a3 - a4;
                hasil.setText(" " + a1 + " - "  + a2 + " - " + a3 + " - " + a4 + " = " + hsl);
            }
        }
        else if(jns.equals("Perkalian")){
            if(jml == 2){
                hsl = a1 * a2;
                hasil.setText(" " + a1 + " - " + a2 + " = " + hsl);
            }
            if(jml == 3){
                hsl = a1 * a2 * a3;
                hasil.setText(" " + a1 + " * " + a2 + " * " + a3 + " = " + hsl);
            }
            if(jml == 4){
                hsl = a1 * a2 * a3 * a4;
                hasil.setText(" " + a1 + " * " + a2 + " * " + a3 + " * " + a4 + " = " + hsl);
            }
        }
        else if(jns.equals("Pembagian")){
            if(jml == 2){
                hsl = a1 / a2;
                hasil.setText(" " + a1 + " : " + a2 + " = " + hsl);
            }
            if(jml == 3){
                hsl = a1 / a2 / a3;
                hasil.setText(" " + a1 + " : " + a2 + " : " + a3 + " = " + hsl);
            }
            if(jml == 4){
                hsl = a1 / a2 / a3 / a4;
                hasil.setText(" " + a1 + " : " + a2 + " : " + a3 + " : " + a4 + " = " + hsl);
            }
        }
    }//GEN-LAST:event_hitungActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Praktikum2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Praktikum2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JLabel bil1;
    private javax.swing.JLabel bil2;
    private javax.swing.JLabel bil3;
    private javax.swing.JLabel bil4;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JComboBox<String> jumlah;
    private javax.swing.JLabel ket;
    // End of variables declaration//GEN-END:variables
}
